env: standard
runtime: python37
instance_class: F1
entrypoint: gunicorn -c gunicorn.conf.py -b :$PORT main:app

inbound_services:
  - warmup

env_variables:
  ABACUS_ENV: ''
  ABACUS_GAE_ENV: standard
  ABACUS_GAE_REGION: us-central1
  FIREBASE_PROJECT_ID: "abacus-dental-auth"
  FIREBASE_PRIVATE_KEY_ID: "476be8362932d2d65989c8d002c9ea524d15247a"
  FIREBASE_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC/C1ZMSbVP63eB\ndzRv1+MkQWaFmYbInQP6tZOUJqekuIWG3OF7q9tQqidJ3BJxaronxlVg8vDsN2iT\nOQNOrnhoiaVGRvLal1+rhwNJMbWHG4UQlqkf93icH779cefq3BX4k3OcScGTUOKF\nmBAws8YKdFnBekRt7YSaFK9vis/n/CYtj7E424v/qISFFXwh0WXpC508AusYkWVY\nkCqH0JYtHBK5S5hfZMVCbMiH/IT7Un1yfBR6G84/Yy2tdmu7885oY4vSR6PBey+u\nlFzoAqPEZD6PAimaopqGKmcE7Ziavy///hCOeQzkPJtsDlmpP2bHojwalWw//6y4\nymcOe2URAgMBAAECggEAE6r8IHB6LRclv3thN553MPVWs6xhluerUDU/U0JDgg7J\nGGBHCm9f7ccGsnDoqSp+rbeadJeuO/NcXcPB1mjZ1pFNJZYKTHzHCaalrPRkJtur\ncFDCapsUnKYcCIWghapQzL2Jam6hciQinfRQvmLToaHm16dZwiNwwlgc05Pr4YsC\n/blBg8AU7NCOW8+HTd+xTPlT2keGuyw7PybJCmq39XN+t9iMTZEg2cPO39fQ+4Yq\nanCQb8+snDXYCbLRJGjPU2Y0iJisjrA+BI+b2ooNRYMM1vY8yV3YiEySC9sMpm2V\nYn9P9EHIh8IcGd8iruqaIMtg93/hhqK6v1JEkjqCUQKBgQD+ErK1GlkMH5R3J4Fk\nb5hoUTYQPRduvPB72awZY1ivRmbS5c0Z8DIEFhmdAWKqHKxUcx7LzAZvtrTRIY+t\nHzY3ySAjMIt9Rjsih5wY5Jl0tGUMOc+NRfQQAJiMjO5NVngIGVrHRV1Se2tztBl2\n3u1DoPPzZVUtp/Nudf9NvR1dNQKBgQDAfkOStsBlgk2uRFnO3mNdtv/TW0vSdibo\n/OXOFwH/3HI8ZfsrEde2x+c8iZKALG0YsnSCc+ABdvHQeqSUEd8tgz3LtTrMKfJH\noSjkgXXdKRpP9zXiH2LZXIMBMTE+11+PZ+Hppe0kehg6MopvcThpEIp5nvJFZ270\nsBsf0z4P7QKBgH9ZPevajgGunoru6UM/UEQRWKjhBirCV0Oswj9jdWM9RXK2Loyu\nwVMdBK+Wry6W+qXFog0CccNy78TXLp3WxCVIEWyx+2jKV/+hu1Ma2fQOK4vqOicU\nhhWzRsNELHnlOnrMwpyZHwKlzCENh6n2aTR5q203QG+G/FREnrgHb311AoGBALyp\nA8F/rAHRPCFYjEzcWbc37HRSPnX/pxMjCnh6xFLo1G2t5gXIbwuN0WzbyOImqKZU\nASz6NMo6sbYK/dLB0WLiBmbpML95PSRHJ7UNzV79MfS97em5qUAwE5XPiNx2ago7\nXoeJQGtH3wbrEhM3fHo84/tfdUPgpDbdgzgl6eXhAoGAG7eYVW6acBDDsa/CDexA\nd1LWtZVu0vnFg2tWdvDPNTcdz6Vx2JrIr5oJ/x8yCZPl0HvLQa03f1gcK9hfFrCv\n6l2o76s7A9JBvLoJ9LctPDM3nwbLQlGF0gqBZK8EHYdHuPRTuthmXgPaBpUtRmNY\nZtmQ9m+FXGDlKX75LwfpU7w=\n-----END PRIVATE KEY-----\n"
  FIREBASE_CLIENT_EMAIL: "firebase-adminsdk-4bjl9@abacus-dental-auth.iam.gserviceaccount.com"
  FIREBASE_CLIENT_ID: "104146861357431819678"
  FIREBASE_CLIENT_CERT_URL: "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-4bjl9%40abacus-dental-auth.iam.gserviceaccount.com"

automatic_scaling:
  max_idle_instances: 1
  max_concurrent_requests: 2

handlers:
  - url: .*
    script: auto
    secure: always
    redirect_http_response_code: 301